
services:
  app:
    image: log-viewer:latest
    env_file: ".env"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/logviewer
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/logviewer
      - DB_MIGRATIONS=database/migrations/*.js
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    env_file: ".env"
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=logviewer
    ports:
      - "5432:5432"
    volumes:
      - ./api/init-scripts:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {} # Empty object means use default Docker volume settings